name: Matrix Test

on:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        version: [v1, v2, v3]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Show OS and Version
        run: |
          echo "Operating System: ${{ matrix.os }}"
          echo "Code Version: ${{ matrix.version }}"
