name: Matrix Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        version: [v1, v2, v3]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Test
        run: |
          echo "OS: ${{ matrix.os }}"
          echo "Version: ${{ matrix.version }}"
